#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/solarsystem
#    username: root
#    password:
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/solarsystem
#    username: root
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update


spring:
  datasource:
    url: jdbc:h2:mem:persondb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
  console:
    enabled: true
    path: /h2-console


