spring:
  datasource:
    url: jdbc:mysql://localhost:3306/solarsystem
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085


