#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/solarsystem
#    username: root
#    password:
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update


spring:
  datasource:
    url: jdbc:mysql://35.232.96.108:3306/solarsystem
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update



server:
  port: 8085


